### ISSUE TITLE
Mały problem z Rzutem na PECH - zamieszczam obraz

### ISSUE THREAD

**Issue by Belial66688** [silentmark/wfrp4e-core-pl#13]
![Zrzut ekranu 2024-07-01 225330](https://github.com/silentmark/wfrp4e-core-pl/assets/174120420/dfe1507a-5498-425b-b778-36ebb011073c)
 
Znalazłem to przed chwilą

**Comment by GregorHak** [comment]
brakuje kropki w linku. Powinno być: ....Compendium.wfrp4e-core.items.nF5z1OEhpi4t6a6S....
