### ISSUE TITLE
Spaczenie Cecha Stworzenia - Błąd Nieprawidłowy poziom Zepsucia

### ISSUE THREAD

**Issue by angello1410** [silentmark/wfrp4e-core-pl#14]
Wrzucam na kartę Cechę Stworzenia Spaczenie -> wybieram Pomniejsze (nie ma znaczenia które wybiorę)
Z karty Efekty wybieram Spaczenie, na czacie dostaję info kto jest źródłem spaczenia i jaki jest poziom.
Klikam Opór i dostaję błąd Nieprawidłowy poziom Zepsucia

Po ręcznej zmianie Pomniejsze -> Minor wszystko działa dobrze

**Comment by GregorHak** [comment]
https://github.com/silentmark/wfrp4e-core-pl/commit/9ee6c5d9c2e8cbc1c755ecffab052242a87fddb5
