### ISSUE TITLE
Tabela Pech - brak powiązania urazu 

### ISSUE THREAD

**Issue by angello1410** [silentmark/wfrp4e-core-pl#16]
Przy rzucie 81-90 w tabeli Pech nie jest podpięty lub jest źle podpięty uraz 

![image](https://github.com/silentmark/wfrp4e-core-pl/assets/11428681/c38510aa-419b-4b02-a599-66294e3ab15d)

**Comment by GregorHak** [comment]
Duplikat
https://github.com/silentmark/wfrp4e-core-pl/issues/13
