### ISSUE TITLE
Błąd w opisie talentu Etykieta

### ISSUE THREAD

**Issue by Myeshko1** [silentmark/wfrp4e-core-pl#17]
![image](https://github.com/silentmark/wfrp4e-core-pl/assets/32203439/7e7d9cbe-4fd8-41df-a6b8-9d5f3bd63d32)

**Comment by GregorHak** [comment]
Ten talent miał update:
https://github.com/silentmark/wfrp4e-core-pl/pull/12/commits/5fd104a4f41adc7de876ea93d70d28f98d7af082

Poprawka choć zaimplementowana już, to nie wchodzi w skład v1.0.4. Trzeba sprawdzić czy wszystko zostało naprawione jak będzie v1.0.5, albo pobierz ręcznie wersje live (patrz obrazek)

![obraz](https://github.com/silentmark/wfrp4e-core-pl/assets/99994770/ef62b150-a581-4dd0-9d66-19d4fb532b2c)

**Comment by silentmark** [comment]
bo nie jest wypuszczone, za jakis czas wrzuce poprawki, jak sie jeszcze cos nazbiera
