### ISSUE TITLE
Problem z wyborem modułu

### ISSUE THREAD

**Issue by Cyrylow** [silentmark/wfrp4e-core-pl#18]
Kiedy wchodzę w świecie w zakłądkę z modułami checkbox jest przyciemniony ze spolszczeniem. Wyświetla się komunikat o brakujących zależnościach. Świat czysty. Mam włączony corebook
![obraz](https://github.com/silentmark/wfrp4e-core-pl/assets/147110076/c058b29d-ae5b-4592-97c8-9727771af3c3)

Oczywiście mam zainstalowaną najnowszą wersję fvtt

**Comment by GregorHak** [comment]
Musisz mieć jeszcze moduł Bebele
https://foundryvtt.com/packages/babele

**Comment by Cyrylow** [comment]
Okazało się że problemem była nieaktualna wersja Babele, dzięki
