### ISSUE TITLE
Problem ze "Zgłaszaniem Skarg"

### ISSUE THREAD

**Issue by Myeshko1** [silentmark/wfrp4e-core-pl#22]
Próbując wysłać zgłoszenie z bugiem związanym z systemem, nie jest to możliwe ponieważ klikając gdziekolwiek na to okienko automatycznie przekierowuje na stronę moomana związaną z troubleshootingiem.
Dzieje się tak jak mam odpalone tłumaczenie. Jak je wyłączyłem jest wszystko OK.
Możliwe że gdzieś w tłumaczeniu kod htmla się wysypał.

![image](https://github.com/user-attachments/assets/6cee2708-034e-4d56-8e2a-47b1828e15fc)

![image](https://github.com/user-attachments/assets/6ae39984-e78f-43ca-9649-fb045b89721b)

**Comment by GregorHak** [comment]
zamykam, naprawione w [v1.1.5](https://github.com/silentmark/wfrp4e-core-pl/releases/tag/v1.1.5)
