### ISSUE TITLE
zmiana nazwy modułu

### ISSUE THREAD

**Issue by GregorHak** [silentmark/wfrp4e-core-pl#28]
Obecna nazwa: "Oficjalne polskie tłumaczenie systemu Warhammer Fantasy Roleplay 4. ed."
Tak wygląda to w zakładce z modułami:

![obraz](https://github.com/user-attachments/assets/ff3f71fd-866a-4698-9566-431b256e1ce5)

proponuje zmianę na coś typu:
"WFRP4e - Polskie tłumaczenie (oficjalne)"

wtedy wpasuje się do nazw Moomana i będzie czytelniejsze
![obraz](https://github.com/user-attachments/assets/21cb9d0f-5df9-4de2-939c-094fb22bc827)

Do rozważenia? Bo każdy po pobraniu modułu sam może sobie zmienić nazwę za pomocą Foundry

**Comment by Myeshko1** [comment]
Też proponowałem, ale bardziej mi pasuje `WFRP4e - Oficjalne polskie tłumaczenie`.
Z nawiastem jakoś tak estetycznie gorzej wygląda.

**Comment by silentmark** [comment]
to trzeba do Pawła z tym uderzyć, taką nazwę otrzymałem.

**Comment by GregorHak** [comment]
@silentmark 

nazwa chyba nie była nigdy zmieniona, mimo że Paweł się zgodził

![Image](https://github.com/user-attachments/assets/f9320332-dc07-4330-bfc4-bff7f7f4fe4f)

**Comment by GregorHak** [comment]
zmienione w Wfrp4e-core-source i wfrp4e-core-pl.
