### ISSUE TITLE
Dostosowanie do nowej wersji systemu 8.0

### ISSUE THREAD

**Issue by rklos** [silentmark/wfrp4e-core-pl#32]
Hej,
kilka dni temu wyszła nowa wersja 8. systemu Warhammera 4ed na Foundry.
Po aktualizacji systemu nie da się włączyć tłumaczenie z powodu braku kompatybilności:
![CleanShot 2024-09-08 at 23 13 28](https://github.com/user-attachments/assets/ac746a4b-3128-430e-947a-ca7da335da92)

**Comment by GregorHak** [comment]
Tłumaczenie nie posiada jeszcze kompatybilności z v8.0.0. oraz Foundry v12. Póki co nie należy używać tłumaczenia z tymi najnowszymi wersjami, bo po prostu coś wykrzaczy. Aktualizacja tłumaczenia na pewno zajmie trochę więcej czasu, ze względu na zmiany MooMana dotyczące Warhammer Library
