### ISSUE TITLE
Problem z profesjami i nakładaniem stanów

### ISSUE THREAD

**Issue by Sythriel** [silentmark/wfrp4e-core-pl#6]
![image](https://github.com/silentmark/wfrp4e-core-pl/assets/174025713/f22c5e0a-8a92-4b92-8d60-a46bc765d407)

**Comment by silentmark** [comment]
@Sythriel czy możesz przekierowywać użytkowników bezpośrednio tutaj w celu zgłaszania błędów? Raz, że jest to normalna praktyka przy większości modułów foundry, dwa, że zdejmie z was jeden dodatkowy obowiązek a trzy, że łatwiej nam będziemy dotrzeć do szczegółów od zgłaszającego. Tutaj napisałem już bezpośrednio przez Messengera i czekam na więcej szczegółów
