### ISSUE TITLE
Problem z inicjalizacją modułu

### ISSUE THREAD

**Issue by MPBrowar** [silentmark/wfrp4e-core-pl#9]
![image](https://github.com/silentmark/wfrp4e-core-pl/assets/174144963/cd728b7b-d1d2-4b4b-9691-4d0d4113b937)
![image](https://github.com/silentmark/wfrp4e-core-pl/assets/174144963/1bbf900f-65dc-48cd-abb4-599c165b3340)
![image](https://github.com/silentmark/wfrp4e-core-pl/assets/174144963/34bf8a09-2ab1-4989-b806-8795d6f85645)
![image](https://github.com/silentmark/wfrp4e-core-pl/assets/174144963/64f6fbe0-63f0-42a6-83aa-ca85999414a5)

Mam problem z uruchomieniem modułu z tłumaczeniem, a konkretnie z odpaleniem inicjalizacji - nic się nie dzieje + błędy w konsoli
nowy świat, babele wersja 2.5.5 (aktualna)

**Comment by silentmark** [comment]
@MPBrowar , czy masz inne moduły z WFRP aktywne oprócz Core?

**Comment by MPBrowar** [comment]
@silentmark , nie, celowo testowałem na nowym świecie, bez aktywowania innych modułów. Mam na innym świecie moduły ze startera, RNHD i UA, ale tam nie włączałem tłumaczenia

**Comment by silentmark** [comment]
@MPBrowar niestety nie udało mi się odtworzyć tego problemu, spróbuj z nową wersją, a jak to nie pomoże, to łap mnie na discordzie.
